---
title: 'Arbeidskrav 2'
output:
  html_document:
    df_print: paged
    toc: true
  pdf_document:
    toc: true 
  word_document:
    toc: true 
lang: nb-NO
bibliography: 
csl: apa-no-ampersand.csl
---
 

# Innledning

# Statistikk

```{r}
library(modelr)
?modelr::heights
x <- modelr::heights
attach(x)
heights$heightInt <- cut(heights$height, breaks = 8)
knitr::kable(summary(heights[,4:9]))
knitr::kable(summary(heights[,5:9]))
knitr::kable(summary(heights[,2]))

```


# Analyse og plots


```{r echo=TRUE}
#install.packages("ggplot2")
library("ggplot2")
ggplot(heights, mapping = aes(x = height, y = income))+geom_point()

```

```{r}
heightsPosInc <- subset(heights, income>0)
ggplot(heightsPosInc, mapping = aes(x = heightInt, y = income)) +
  scale_y_continuous(trans = scales::log_trans()) +
  geom_boxplot()
```

```{r}
heightsPosInc <- subset(heights, income>0)
ggplot(heightsPosInc, mapping = aes(x = height, y = income)) +
  scale_y_continuous(trans = scales::log_trans()) +
  geom_point(position = "jitter") +
  geom_smooth(method = "lm")
```

```{r}
heightsPosInc <- subset(heights, income>0)
ggplot(heightsPosInc, mapping = aes(x = height, y = income)) + 
  geom_point(position = "jitter") +
  geom_smooth(method = "lm")
```

```{r}
summary(lm(income~height, data = heights))
```

# Våre funn vs tidligere forskning

# Konklusjon

Her er arbeidskrav 2. 


